
sounds = {
  { -- 0 ; bonus pickup
    attack = 0,
    decay = 0.2,
    sustain = 0,
    sustainPunch = 0,
    tremoloDepth = 0,
    tremoloFrequency = 10,
    frequency = 500,
    frequencyDeltaSweep = 5000,
    frequencyJump1Onset = 0,
    frequencyJump2Onset = 0,
    frequencyJump1Amount = 0,
    frequencyJump2Amount = 0,
    frequencySweep = 0,
    vibratoFrequency = 0,
    vibratoDepth = 0,
    flangerOffset = 0,
    flangerOffsetSweep = 0,
    repeatFrequency = 15,
    waveform = 'triangle',
    amplification = 0.5,
  },
  { -- 1 ; player_bullet shoot
    attack = 0.1,
    decay = 0,
    sustain = 0,
    sustainPunch = 0,
    tremoloDepth = 0,
    tremoloFrequency = 0,
    frequency = 1000,
    frequencyDeltaSweep = -990,
    frequencyJump1Onset = 0,
    frequencyJump2Onset = 0,
    frequencyJump1Amount = 0,
    frequencyJump2Amount = 0,
    frequencySweep = 0,
    vibratoFrequency = 0,
    vibratoDepth = 0,
    flangerOffset = 0,
    flangerOffsetSweep = 0,
    repeatFrequency = 0,
    waveform = 'sine',
    amplification = 0.03,
  },
  { -- 2 ; pinky shoot
    attack = 0.1,
    decay = 0,
    sustain = 0,
    sustainPunch = 0,
    tremoloDepth = 0,
    tremoloFrequency = 0,
    frequency = 600,
    frequencyDeltaSweep = -550,
    frequencyJump1Onset = 0,
    frequencyJump2Onset = 0,
    frequencyJump1Amount = 0,
    frequencyJump2Amount = 0,
    frequencySweep = 0,
    vibratoFrequency = 0,
    vibratoDepth = 0,
    flangerOffset = 0,
    flangerOffsetSweep = 0,
    repeatFrequency = 0,
    waveform = 'whistle',
    amplification = 0.02,
  },
  { -- 3 ; candy shoot
    attack = 0.1,
    decay = 0,
    sustain = 0,
    sustainPunch = 0,
    tremoloDepth = 0,
    tremoloFrequency = 0,
    frequency = 600,
    frequencyDeltaSweep = -550,
    frequencyJump1Onset = 0,
    frequencyJump2Onset = 0,
    frequencyJump1Amount = 0,
    frequencyJump2Amount = 0,
    frequencySweep = 0,
    vibratoFrequency = 0,
    vibratoDepth = 0,
    flangerOffset = 0,
    flangerOffsetSweep = 0,
    repeatFrequency = 0,
    waveform = 'whistle',
    amplification = 0.05,
  },
  { -- 4 ; potato shoot
    attack = 0.1,
    decay = 0,
    sustain = 0,
    sustainPunch = 0,
    tremoloDepth = 0,
    tremoloFrequency = 0,
    frequency = 200,
    frequencyDeltaSweep = -150,
    frequencyJump1Onset = 0,
    frequencyJump2Onset = 0,
    frequencyJump1Amount = 0,
    frequencyJump2Amount = 0,
    frequencySweep = 0,
    vibratoFrequency = 0,
    vibratoDepth = 0,
    flangerOffset = 0,
    flangerOffsetSweep = 0,
    repeatFrequency = 0,
    waveform = 'sine',
    amplification = 0.05,
  },
  { -- 5 ; star damaged
    attack = 0,
    decay = 0.1,
    sustain = 0,
    sustainPunch = 0,
    tremoloDepth = 0,
    tremoloFrequency = 0,
    frequency = 750,
    frequencyDeltaSweep = 1000,
    frequencyJump1Onset = 0,
    frequencyJump2Onset = 0,
    frequencyJump1Amount = 0,
    frequencyJump2Amount = 0,
    frequencySweep = 0,
    vibratoFrequency = 0,
    vibratoDepth = 0,
    flangerOffset = 0,
    flangerOffsetSweep = 0,
    repeatFrequency = 0,
    waveform = 'sine',
    amplification = 0.6,
  },
  { -- 6 ; star death
    attack = 0,
    decay = 0.25,
    sustain = 0,
    sustainPunch = 0,
    tremoloDepth = 0,
    tremoloFrequency = 0,
    frequency = 1000,
    frequencyDeltaSweep = 2000,
    frequencyJump1Onset = 0,
    frequencyJump2Onset = 0,
    frequencyJump1Amount = 0,
    frequencyJump2Amount = 0,
    frequencySweep = 0,
    vibratoFrequency = 0,
    vibratoDepth = 0,
    flangerOffset = 0,
    flangerOffsetSweep = 0,
    repeatFrequency = 0,
    waveform = 'sine',
    amplification = 0.75,
  },
  { -- 7 ; sentry damaged
    attack = 0,
    decay = 0.04,
    sustain = 0,
    sustainPunch = 0,
    tremoloDepth = 0,
    tremoloFrequency = 0,
    frequency = 500,
    frequencyDeltaSweep = 1500,
    frequencyJump1Onset = 0,
    frequencyJump2Onset = 0,
    frequencyJump1Amount = 0,
    frequencyJump2Amount = 0,
    frequencySweep = 0,
    vibratoFrequency = 0,
    vibratoDepth = 0,
    flangerOffset = 0,
    flangerOffsetSweep = 0,
    repeatFrequency = 0,
    waveform = 'triangle',
    amplification = 1,
  },
  { -- 8 ; sentry death
    attack = 0,
    decay = 0.25,
    sustain = 0,
    sustainPunch = 0,
    tremoloDepth = 0,
    tremoloFrequency = 0,
    frequency = 500,
    frequencyDeltaSweep = 3500,
    frequencyJump1Onset = 0,
    frequencyJump2Onset = 0,
    frequencyJump1Amount = 0,
    frequencyJump2Amount = 0,
    frequencySweep = 0,
    vibratoFrequency = 0,
    vibratoDepth = 0,
    flangerOffset = 0,
    flangerOffsetSweep = 0,
    repeatFrequency = 15,
    waveform = 'triangle',
    amplification = 1,
  },
  { -- 9 ; cube damaged
    attack = 0,
    decay = 0.02,
    sustain = 0,
    sustainPunch = 0,
    tremoloDepth = 0,
    tremoloFrequency = 0,
    frequency = 2500,
    frequencyDeltaSweep = -5000,
    frequencyJump1Onset = 0,
    frequencyJump2Onset = 0,
    frequencyJump1Amount = 0,
    frequencyJump2Amount = 0,
    frequencySweep = 0,
    vibratoFrequency = 0,
    vibratoDepth = 0,
    flangerOffset = 0,
    flangerOffsetSweep = 0,
    repeatFrequency = 0,
    waveform = 'sine',
    amplification = 1,
  },
  { -- 10 ; cube death
    attack = 0,
    decay = 0.6,
    sustain = 0,
    sustainPunch = 0,
    tremoloDepth = 0,
    tremoloFrequency = 0,
    frequency = 1500,
    frequencyDeltaSweep = 7500,
    frequencyJump1Onset = 0,
    frequencyJump2Onset = 0,
    frequencyJump1Amount = 0,
    frequencyJump2Amount = 0,
    frequencySweep = 0,
    vibratoFrequency = 0,
    vibratoDepth = 0,
    flangerOffset = 0,
    flangerOffsetSweep = 0,
    repeatFrequency = 15,
    waveform = 'sine',
    amplification = 1,
  },
  { -- 11 ; laser shoot
    attack = 0,
    decay = 0.02,
    sustain = 0.08,
    sustainPunch = 0,
    tremoloDepth = 0,
    tremoloFrequency = 0,
    frequency = 1500,
    frequencyDeltaSweep = -800,
    frequencyJump1Onset = 0,
    frequencyJump2Onset = 0,
    frequencyJump1Amount = 0,
    frequencyJump2Amount = 0,
    frequencySweep = -800,
    vibratoFrequency = 0,
    vibratoDepth = 0,
    flangerOffset = 0,
    flangerOffsetSweep = 0,
    repeatFrequency = 15,
    waveform = 'whistle',
    amplification = 0.02,
  }
}
